### PR TITLE
User authorization

### PR DESCRIPTION
**Pull request by advantagevarnson**
@droberts84

### CODE REVIEW

**Comment by advantagevarnson** [comment]
i have updated to letter opener and ive added 
```
              <% if policy(bookmark).update? %>
                <%= link_to "Edit Bookmark", edit_topic_bookmark_path(@topic, bookmark), class: 'btn btn-success' %>
              <% end %>
```
within the topics show, however im getting a no method error for policy?
is there something im missing?

**Comment by droberts84** [comment]
What method is missing? The error message should point you to the source

**Comment by advantagevarnson** [comment]
undefined method `policy' for #<#<Class:0x007fbc66172378>:0x007fbc6aadc928>

its in the topics show view

**Comment by advantagevarnson** [comment]
sorted it.

**Pull request merged**
